### ISSUE TITLE
O3653-3 Graph Service Exception thrown

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#100]
Module Number: O3653-3
Module Title: Microsoft Graph for OneDrive for Business Ex. 2
Path of file:
### Details of issue
I got this error when building from Exercise 2.

![image](https://cloud.githubusercontent.com/assets/17051339/14091822/570ae4c2-f4f7-11e5-9c39-7beef7a6b257.png)

**Comment by rgregg** [comment]
You opened this one previously, and I said I couldn't repro it. Can you provide more details (fiddler trace, accounts being used, etc)?

**Comment by lucas66** [comment]
The credentials used were not admin.  I verified with admin credentials.  Issue closed.
