### ISSUE TITLE
O3653-19 Webhooks cannot get Microsoft.Graph from package manager console

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#107]
Module Number: O3653-19
Module Title: Get notified when data changes through Microsoft Graph Webhooks
Path of file:
### Details of issue
The Package Manager Console shows this error when trying to get MS Graph.  I can install MS Graph from the UI and I can get SignalR using the console.  Might be a nuget issue.

![image](https://cloud.githubusercontent.com/assets/17051339/14125925/97137892-f5c2-11e5-84cc-fbd3e7474812.png)

**Comment by DianeD** [comment]
thanks @lucas66 Yes, we'll be testing and updating the package/lab instructions soon.

**Comment by DianeD** [comment]
Install-Package Microsoft.Graph from package manager console working now. No change to lab instructions needed.
