### ISSUE TITLE
O3653-20 OfficeGraph "Type 'Chart' already defines a member called 'Image' with the same parameter types" Error

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#109]
Module Number: O3653-20
Module Title: Insights from Microsoft Graph
Path of file:
### Details of issue
After deploying from Exercise 5, the following error is displayed

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0111	Type 'Chart' already defines a member called 'Image' with the same parameter types	OfficeGraphLab	C:\Dev\OfficeGraphLab\OfficeGraphLab\Graph.cs	59433	Active

**Comment by jakubcech** [comment]
Hey, thanks for taking the time to do the lab and reporting this. This looks to be the same issue as:
https://github.com/OfficeDev/office-docs/issues/103

Which should be resolved soon as the beta endpoint is getting updated. Did you build the solution after exercise 5 for the first time btw.? As this is something that should happen after Exercise 2.

**Comment by jakubcech** [comment]
This shouldn't be an issue anymore.
