### ISSUE TITLE
instructions in the webhooks lab return an error

### ISSUE THREAD

**Issue by JuaneloJuanelo** [OfficeDev/office-docs#111]
Module Number:  O3653 / O3653-19 WebHooks
Module Title:   O3653-19 WebHooks
Path of file: https://github.com/OfficeDev/office-docs/blob/master/O3653/O3653-19%20WebHooks/Lab.md

### Details of issue
Excercise 1 step 5 is failing on the test VM whrn trying to install the Microsoft.Graph

here is the error on the package manager console..

PM> Install-Package Microsoft.Graph
Install-Package : Unable to find package 'Microsoft.Graph'
At line:1 char:1
+ Install-Package Microsoft.Graph
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement 
   .PowerShellCmdlets.InstallPackageCommand

**Comment by DianeD** [comment]
Juan, this is currently expected behavior. If you can install the Graph SDK using the Nuget Package Manager UI for now and continue testing, that’d be great..

**Comment by DianeD** [comment]
Install-Package Microsoft.Graph from package manager console working now
