### ISSUE TITLE
O3659-1 WebSDK - line numbering not formatted correctly

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/office-docs#21]
Module: O3659-1
Title: O3659-1 WebSDK 
File name affected: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3659/O3659-1%20WebSDK/Skype_for_Business_Web_SDK.md
### Details of issue
The line numbering markdown is not rendering correctly. The line numbers run together instead of being on separate lines.

**Comment by davnewman** [comment]
Hi @davidchesnut can you elaborate on this issue?  I'm not clear on what is not rendering or how I can fix it

**Comment by davidchesnut** [comment]
Well, never mind. The line numbers look fine now. Thanks for checking. :+1:
