### ISSUE TITLE
 O3652-3 - Blocked by prereq tooling problem

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/office-docs#33]
Module Number: O3652-3
Module Title: Deep Dive in Office PowerPoint Add-ins
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3652/O3652-3%20Deep%20Dive%20in%20Office%20PowerPoint%20Add-ins/QuickStart.md 
### Details of issue
I can't complete testing because I get errors when running the add-in from Visual Studio. I suspect this may be a problem with the Office Developer Tools which I downloaded from here:
\\cpvsbuild\Drops\CBA\master\layouts\x86ret\23914.00\enu\cba\bundle\web 

I have tried this with two configurations.
### Config 1
I ran with Visual Studio 2015, Office Developer Tools, and *Dogfood Office*. I get the following error when clicking Start

```
------ Build started: Project: HelloWorld2, Configuration: Debug Any CPU ------
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\SharePointTools\Microsoft.VisualStudio.SharePoint.targets(450,5): error : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
```

### Config 2
I ran with Visual Studio 2015, Office Developer Tools, and *RTM Office 2016*. I get the following error when clicking Start.

```
Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.5.5631.0, Culture... etc... The system cannot find the file specified.
```

**Comment by keyur32** [comment]
closing this - not relavent to the build environment. David - hope you do find an issue on your local machine and happy to help after build
