### ISSUE TITLE
O3653-13 - Microsoft Graph for Calendar

### ISSUE THREAD

**Issue by jthake** [OfficeDev/office-docs#35]
Module Number: O3653-13
Module Title: Microsoft Graph for Calendar
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3653/O3653-13%20Deep%20Dive%20into%20Office%20365%20APIs%20for%20Calendar/CalendarQuickStartLab%20-%20Copy.md
### Details of issue

- [x] update title and description to match collab db
- [x] remove the Prerequisites section as these labs will be done on the VM
- [x] you have two Exercise 1 headings.
- [x] **you cannot have tested these instructions**. the app name is 'Graph Calendar Quick Start' one of these is a banned word for an app name
- [x] you've got a bunch of methods that are missing closing brackets in code snippets e.g. Index and AddEvents
- [x] You actually need to have a step to remove the default Index method for this view to work properly
- [x] StripHTML does not resolve in the controller after following steps
- [x] the layouts.cshtml view code you ref doesn't include `<li>@Html.ActionLink("Graph API", "Graph", "Home")</li>`
- [x] it states 'Select MVC View Page' but in Visual Studio it says 'MVC 5 View Page (Razor)'

- [x] when I F5, I get this error clicking the view `Access token validation failure..` and this in Fiddler. Looking your code `https://outlook.office.com/calendars.readwrite` should be `https://graph.microsoft.com/calendars.readwrite` 

````
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Server: Microsoft-IIS/8.5
request-id: 758c4747-87c3-4d2b-bde8-2c3e06095d7f
client-request-id: 758c4747-87c3-4d2b-bde8-2c3e06095d7f
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US","Slice":"SliceA","ScaleUnit":"002","Host":"AGSFE_IN_1","ADSiteName":"WST"}}
X-Powered-By: ASP.NET
Date: Tue, 15 Mar 2016 22:33:18 GMT
Content-Length: 244

{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure.",
    "innerError": {
      "request-id": "758c4747-87c3-4d2b-bde8-2c3e06095d7f",
      "date": "2016-03-15T22:33:18"
    }
  }
}
````

**Comment by abdelbahgat** [comment]
Updated the title and description in collabdb to match the lab content.
