### ISSUE TITLE
O3652-2 Compliance review: add alt text for all images

### ISSUE THREAD

**Issue by beckandros** [OfficeDev/office-docs#37]
Module Number: O3652-2 
Module Title:  Deep Dive in Office Word Add-ins 
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3652/O3652-2%20Deep%20Dive%20in%20Office%20Word%20Add-ins/Lab.md

**Comment by keyur32** [comment]
not critical for build
