### ISSUE TITLE
O3652-2 Compliance review: Office 2016 preview mention

### ISSUE THREAD

**Issue by beckandros** [OfficeDev/office-docs#38]
Module Number: O3652 / O3652-2 Deep Dive in Office Word Add-ins / 
Module Title: O3652 / O3652-2 Deep Dive in Office Word Add-ins / 
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3652/O3652-2%20Deep%20Dive%20in%20Office%20Word%20Add-ins/Lab.md
### Details of issue
Mention of Office 2016 Preview in prereqs okay?

**Comment by JuaneloJuanelo** [comment]
The pre reqs section was removed, and not needed
