### ISSUE TITLE
O3652-3 - editing and markdown problems found

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/office-docs#39]
Module Number: O3652-3
Module Title: Deep Dive in Office PowerPoint Add-ins
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3652/O3652-3%20Deep%20Dive%20in%20Office%20PowerPoint%20Add-ins/QuickStart.md
### Details of issue
Found the following issues

### Edit pass
overall this page needs an edit pass, and markdown cleanup in a few spots. Example there are some extra asterisks that should not appear, and the word Excersize is misspelled. Bolding and some steps need some rework to follow our style guide.

### Prerequisites:
- Need to add the link to download the Office Developer Tools.
- Need a link to download Visual Studio. Can they use a free version?

### Steps
- Step 1 to launch VS as admin. Recommend adding steps to do this.
- Step 6 about the command xml. Would be good to link to documentation that explains what each of the xml elements does for more info if someone is interested.
- Step 10 I would show the xml that they need to change (highlight it maybe) rather than rely that they will successfully find it. Found I had to think about this because there are several similarly named XML elements.
- Exercise 2: Step 10: Says there will be a VideosController class, should be PhotoController

**Comment by keyur32** [comment]
The link recommendations won't work out too well from the quick start perspective. Can add them when we make it a training on dev.office.com.  Others are fixed
