### ISSUE TITLE
O3652-2 Compliance review: Update figures for "apps"

### ISSUE THREAD

**Issue by beckandros** [OfficeDev/office-docs#40]
Module Number:  O3652-2 
Module Title:  Deep Dive in Office Word Add-ins 
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3652/O3652-2%20Deep%20Dive%20in%20Office%20Word%20Add-ins/Lab.md
### Details of issue
Search for "evertything" in code blocks and replace with "everything"--couldn't get doc to validate if I fixed it. Sorry!
Fig 3: correct to say "Office applications" not Office client? If not, fix in step text, too.
Figs 4, 5, 6: Title has typo: StatmentOfWork,  StatmentOfWorkManifest,  StatmentOfWorkWeb (missing e in Statement) and "apps" mentioned in Fig 5
Fig 7, 8, 9, 10-12, : Juan's name is in the title bar for the document--ok? Is he in the fictitious names list?

**Comment by keyur32** [comment]
These seem tobe fixed up
