### ISSUE TITLE
O3652-2 Compliance review: Lab.md file name

### ISSUE THREAD

**Issue by beckandros** [OfficeDev/office-docs#41]
Module Number:  O3652-2 
Module Title:  Deep Dive in Office Word Add-ins 
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/tree/master/O3652/O3652-2%20Deep%20Dive%20in%20Office%20Word%20Add-ins
### Details of issue
Lab.md filename not consistent with the QuickStartLab.md file name convention in other modules

**Comment by keyur32** [comment]
Hey, we actually need to call them Lab.md. I'm closing this.
