### ISSUE TITLE
O3653-16 Compliance review: Need alt text for figures, 1 figure not rendering

### ISSUE THREAD

**Issue by beckandros** [OfficeDev/office-docs#45]
Module Number: O3653-16
Module Title: Excel REST API
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3653/O3653-16%20Excel/undefined
### Details of issue
![](images/ToDoworkbook.JPG) not rendering
All figures need alt text

**Comment by keyur32** [comment]
not critical for build
