### ISSUE TITLE
Compliance review: Update title of O3652-2 

### ISSUE THREAD

**Issue by beckandros** [OfficeDev/office-docs#46]
Module Number: O3652-2 
Module Title: Deep Dive in Office Word Add-ins 
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3652/O3652-2%20Deep%20Dive%20in%20Office%20Word%20Add-ins/Lab.md
### Details of issue
Change the title to remove "Office" for consistency. We either refer to Office Add-ins or Word add-ins.

**Comment by keyur32** [comment]
not critical for build.
