### ISSUE TITLE
Compliance review - use fictitious names in O3653-2

### ISSUE THREAD

**Issue by Lauragra** [OfficeDev/office-docs#48]
Module Number: O3653-2
Module Title: Deep Dive into O365 APIs for Calendar, Mail, and Contacts
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3653/O3653-2%20Deep%20Dive%20into%20Office%20365%20APIs%20for%20Calendar%2C%20Mail%2C%20and%20Contacts/Lab.md
### Details of issue
The figure that shows the Messages menu option shows real names/email addresses. Those should be redacted or replaced with approved fictitious names.

**Comment by jthake** [comment]
Not a big drama at this stage so closing.
