### ISSUE TITLE
O3652-16 Exercise 3: Debug HelloWorld add-in using VorlonJS did not complete successfully

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/office-docs#57]
Module Number: `O3652-16-Create-and-test-your-add-in-on-a-Mac-or-iPad`
Module Title: **Create, test, and debug your add-in on a Mac or iPad**
Path of file: `trainingcontent-NDA/O3652/O3652-16-Create-and-test-your-add-in-on-a-Mac-or-iPad/lab.md`

### Details of issue
Followed steps - able to load scripts/Vorlon, but seemingly not from office....

See below:

Script is loading but nothing in Vorlon....

<img width="1429" alt="screen shot 2016-03-16 at 5 36 50 pm" src="https://cloud.githubusercontent.com/assets/990063/13832934/03b2b230-eb9e-11e5-9065-9430a8e7d20f.png">

<img width="1224" alt="screen shot 2016-03-16 at 5 39 49 pm" src="https://cloud.githubusercontent.com/assets/990063/13832946/23c5fd66-eb9e-11e5-8d2d-8687b2180afd.png">

BUT.... if I just spin up an empty page, I can see it....

<img width="820" alt="screen shot 2016-03-16 at 5 38 43 pm" src="https://cloud.githubusercontent.com/assets/990063/13832956/36d93c42-eb9e-11e5-8ba4-2dfb3ecdf7dd.png">
<img width="1410" alt="screen shot 2016-03-16 at 5 36 28 pm" src="https://cloud.githubusercontent.com/assets/990063/13832964/3e14c9ae-eb9e-11e5-9db2-3a70b47075d2.png">

**Comment by smaremanda** [comment]
this was happening because Vorlon and Office add-in werent on the same protocol [http vs https]. Updated quick start
