### ISSUE TITLE
MongoDB not available in classic Azure - O3653-22 Synchronize Outlook data

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/office-docs#58]
Module Number: O3653-22 
Module Title: Synchronize Outlook data
Path of file: 
### Details of issue
This lab requires MongoDB setup. There are two issues with this:
1. This is not suitable for a 20-minute quick-start. This will take a lot more time to complete even when things work well.
2. MongoDB is not available on all accounts yet. When I use my Azure account to create a new MongoDB, I get the following message: "We're working to add services to the new Azure portal, but we're not quite there. If you want to get started now, sign into the Azure classic portal." 
> I tried the classic portal. I didn't see any UI based option to create a MongoDB. At least its not straight forward. Could re-evaluate the scope of this quick-start? Could we use alternate storage instead of Mongo-DB (lightweight - file/JSON maybe)?

**Comment by keyur32** [comment]
sounds like this one is closed and no actions are needed. closing.

**Comment by sumurthy** [comment]
It should work with direct mongo do link. May need some extra time to complete the exercise..
