### ISSUE TITLE
 Compliance review: O3653-18, step numbering--can't fix 

### ISSUE THREAD

**Issue by beckandros** [OfficeDev/office-docs#68]
Module Number: O3653-18
Module Title: Microsoft Graph People API
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3653/O3653-18%20People/undefined
### Details of issue
Exercise 3, Edit the default layout to point to our new controller, step 2: can't get the 2 substeps to number correctly as 1 and 2.

**Comment by edwardthMSFT** [comment]
Fixed
