### ISSUE TITLE
Compliance Review: O3653-17

### ISSUE THREAD

**Issue by toddmackmsft** [OfficeDev/office-docs#69]
Title: Connect to people with the Microsoft Graph, find a colleague/contact even if I don’t know how to spell their name
Module Number: O3653-17
Module Title: Microsoft Graph to manage groups and users
Path of file: https://github.com/OfficeDev/trainingcontent-NDA/blob/master/O3653/O3653-18%20People/lab.md

Details of issue:

- Per Microsoft Accessibility, verify alt text for all images.
- Numbering appears to be corrupt in several exercises.

**Comment by keyur32** [comment]
numbers are fixed up (couldn't repro). accessibility not critical for build
