### ISSUE TITLE
Valid security certificate error in O3652-18

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#84]
Module Number: O3652-18
Module Title: Create and Test an Office Add-in in Excel Online
Path of file:
### Details of issue
I can upload the add-in, but when it tries to activate, I get this error:
Content was blocked because it was not signed by a valid security certificate

**Comment by hshapley** [comment]
@jthake That is not my lab, it's Sudheer's. But if he's not willing to update it, I can update it. Those instructions are super incomplete right now.

**Comment by hshapley** [comment]
The original issue is with my lab, but you linked to a different one (Sudheer's Mac one). Both have issues, mine just the cert issue but Sudheer's that and others.

**Comment by hshapley** [comment]
Fixed the VM template to have the trusted security cert. i will open a new issue for Sudheer to update his lab.
