### ISSUE TITLE
Skype for Business Online Web SDK - starter files

### ISSUE THREAD

**Issue by jthake** [OfficeDev/office-docs#90]
Module Number: O3659/O3659-1 WebSDK
Module Title: Skype for Business Online Web SDK
Path of file: https://github.com/OfficeDev/office-docs/blob/master/O3659/O3659-1%20WebSDK/Skype_for_Business_Web_SDK.md

### Details of issue

It references this location
C:\\Projects\Build2016\LabA\LabAWeb.sln.

The git repo is located at c:\git need to change all refernces.

**Comment by davnewman** [comment]
Fixed
