### ISSUE TITLE
Offce-docs O3653-3 Audience validation failed

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#92]
Module Number: O3653-3 Exercise 2
Module Title:  Microsoft Graph for OneDrive for BusinessPath of file:
### Details of issue
App throws an error when deployed at the end of exercise 2.  

![image](https://cloud.githubusercontent.com/assets/17051339/14051030/2f361d08-f27d-11e5-912a-28f38b436472.png)

**Comment by rgregg** [comment]
@lucas66 Do you have any more details about what steps you did?

**Comment by rgregg** [comment]
I can't reproduce this and audience validation should be disabled in the template we're using anyway.
