### ISSUE TITLE
O3653-7 MS login Bad request

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#93]
Module Number: O3653-7
Module Title: Microsoft Graph for OneNote Services
Path of file:
### Details of issue

I am unable to sign in with BuildChallenge credentials for Exercise 1

![image](https://cloud.githubusercontent.com/assets/17051339/14052840/64a9905c-f28a-11e5-8936-2fa6ec6e8e25.png)

**Comment by DianeD** [comment]
@vsharma77 just making sure you're aware of this, thanks

**Comment by vsharma77** [comment]
This seems to be same issue as #94 . Did you try it again?

**Comment by jasonjoh** [comment]
I wouldn't assume this is the same issue. You don't show the entire screen there, but if you don't see this lower down:

```
Additional technical information: 
Correlation ID: 1be77426-5261-41dd-9bd7-e650608a4e82 
Timestamp: 2016-03-28 20:18:11Z 
AADSTS90093: Calling principal cannot consent due to lack of permissions. 
```

You have a different issue.

**Comment by DianeD** [comment]
no longer repro-ing
