### ISSUE TITLE
O3654-1 Cannot find OAuth2 reference

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#95]
Module Number: O3654-1 Exercise 4
Module Title: Connect to the Microsoft Graph from a Windows Universal App
Path of file:
### Details of issue
Exercise 4 doesn't build because it can't find the Microsoft.Graph.OAuth2 reference after importing Microsoft Graph from NuGet.
![image](https://cloud.githubusercontent.com/assets/17051339/14054104/c0ed3298-f293-11e5-97f0-0b95fca44a49.png)

**Comment by jthake** [comment]
I have to do a git pull to get the SDKs down onto the student lab. I'm doing this now. and will update this issue. Then @lucas66 can you retest and close the issue if it is fixed?

**Comment by lucas66** [comment]
Yes, will do.

**Comment by jthake** [comment]
The lab vm is being rebuilt right now. a new git pull was down in the master VM to pull down the changes.

**Comment by jamescro** [comment]
Latest update to the vm resolves this.
