### ISSUE TITLE
O3654-1 MS login issue

### ISSUE THREAD

**Issue by lucas66** [OfficeDev/office-docs#98]
Module Number: O3654-1
Module Title: Connect to the Microsoft Graph from a Windows Universal App
Path of file:
### Details of issue

MS login issue Bad Request after sign in.
![image](https://cloud.githubusercontent.com/assets/17051339/14086267/1e661da8-f4d9-11e5-82b1-171a02534f8f.png)

**Comment by jamescro** [comment]
Did you click Save after adding the mobile platform to your client? We've seen this very same error occur several times just because we neglected to click the "Save" button after adding the mobile platform.

**Comment by lucas66** [comment]
Thanks Jim. <face palm> Verified.  Please close the bug.
