### ISSUE TITLE
O3652-16 Instructions need to be updated.

### ISSUE THREAD

**Issue by hshapley** [OfficeDev/office-docs#99]
Module Title: Create, test, and debug your add-in on a Mac or iPad
### Details of issue
Sudheer, you need to update your lab, there are many things that are out of date related to yeoman. The easiest thing would be to look at my lab, O3652-18, and use/copy the relevant parts. At a quick glance, here are some of the bigger offenders:

- An O365 tenant is not required. I think this was automatically added to all labs, but i removed it from mine since it's not required.
- Users will not need to install the prerequisites, they'll already be installed on the lab machines. 
- They also will not need to trust the security certificate, that will already be trusted.
- Don't give them so many options, like "you can host it with a different technology" or "you can use something other than VS code". Tell them prescriptively to use VS code and gulp. 

Another suggestion is that you have the developers change/add something to the add-in so that they get a better sense of how add-ins work and what it's like to edit them.

**Comment by smaremanda** [comment]
great - thanks for the suggestions. Updated the doc, will be updating with an Exercise 4 - editing the add-in project once I have my mac back.
